/**
 * Created by lengung on 20/05/2016.
 */

export const GET_GROUPS = 'GET_GROUPS';
export const GET_CONTACTS = 'GET_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT'
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const FILTER_CONTACT = 'FILTER_CONTACT';
export const SELECT_ALL_CONTACT = 'SELECT_ALL_CONTACT';
export const SELECT_OTHER_GROUP_CONTACT = 'SELECT_OTHER_GROUP_CONTACT';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const FILTER_GROUP = 'FILTER_GROUP';
export const IS_ALLOW_CREATE_NEW_GROUP = 'IS_ALLOW_CREATE_NEW_GROUP';
export const IS_ALLOW_ADD_TO_GROUP = 'IS_ALLOW_ADD_TO_GROUP';
export const LOAD_CONTACT_EDIT = 'LOAD_CONTACT_EDIT';
export const IS_ALLOW_REMOVE_CONTACT_FROM_GROUP = 'IS_ALLOW_REMOVE_CONTACT_FROM_GROUP';
export const IS_ALLOW_DELETE_CONTACT='IS_ALLOW_DELETE_CONTACT';


